"""Inicial

Revision ID: e9245d86491d
Revises: 
Create Date: 2025-12-04 11:15:00.955170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9245d86491d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_docente'))
    )
    op.create_table('experimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('generaciones', sa.Integer(), nullable=True),
    sa.Column('poblacion', sa.Integer(), nullable=True),
    sa.Column('elite', sa.Integer(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('num_grupos_total', sa.Integer(), nullable=True),
    sa.Column('num_grupos_m', sa.Integer(), nullable=True),
    sa.Column('num_grupos_v', sa.Integer(), nullable=True),
    sa.Column('best_final', sa.Float(), nullable=True),
    sa.Column('avg_final', sa.Float(), nullable=True),
    sa.Column('tiempo_total', sa.Float(), nullable=True),
    sa.Column('conflictos_docente', sa.Integer(), nullable=True),
    sa.Column('violacion_reserva', sa.Integer(), nullable=True),
    sa.Column('violacion_disponibilidad', sa.Integer(), nullable=True),
    sa.Column('turno_incorrecto', sa.Integer(), nullable=True),
    sa.Column('exceso_sesiones', sa.Integer(), nullable=True),
    sa.Column('falta_sesiones', sa.Integer(), nullable=True),
    sa.Column('exceso_bloques_dia', sa.Integer(), nullable=True),
    sa.Column('exceso_bloques_consecutivos', sa.Integer(), nullable=True),
    sa.Column('exceso_horas_semanales', sa.Integer(), nullable=True),
    sa.Column('fig_fitness', sa.String(length=255), nullable=True),
    sa.Column('fig_hard', sa.String(length=255), nullable=True),
    sa.Column('log_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experimento'))
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('turno', sa.Enum('MATUTINO', 'VESPERTINO', name='turno'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo')),
    sa.UniqueConstraint('nombre', name=op.f('uq_grupo_nombre'))
    )
    op.create_table('materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=140), nullable=False),
    sa.Column('turno', sa.Enum('MATUTINO', 'VESPERTINO', name='turno'), nullable=False),
    sa.Column('bloques_duracion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materia')),
    sa.UniqueConstraint('nombre', name=op.f('uq_materia_nombre'))
    )
    op.create_table('disponibilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('turno', sa.Enum('MATUTINO', 'VESPERTINO', name='turno'), nullable=False),
    sa.Column('bloque_inicio', sa.Integer(), nullable=False),
    sa.Column('bloque_fin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], name=op.f('fk_disponibilidad_docente_id_docente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disponibilidad'))
    )
    op.create_table('docente_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], name=op.f('fk_docente_materia_docente_id_docente')),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], name=op.f('fk_docente_materia_materia_id_materia')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_docente_materia'))
    )
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('turno', sa.Enum('MATUTINO', 'VESPERTINO', name='turno'), nullable=False),
    sa.Column('bloque_inicio', sa.Integer(), nullable=False),
    sa.Column('bloque_fin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], name=op.f('fk_horario_docente_id_docente')),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_horario_grupo_id_grupo')),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], name=op.f('fk_horario_materia_id_materia')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_horario'))
    )
    op.create_table('materia_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('sesiones_por_semana', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_materia_grupo_grupo_id_grupo')),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], name=op.f('fk_materia_grupo_materia_id_materia')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materia_grupo'))
    )
    op.create_table('reserva_modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('turno', sa.Enum('MATUTINO', 'VESPERTINO', name='turno'), nullable=False),
    sa.Column('bloque_inicio', sa.Integer(), nullable=False),
    sa.Column('bloque_fin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_reserva_modulo_grupo_id_grupo')),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], name=op.f('fk_reserva_modulo_materia_id_materia')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reserva_modulo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva_modulo')
    op.drop_table('materia_grupo')
    op.drop_table('horario')
    op.drop_table('docente_materia')
    op.drop_table('disponibilidad')
    op.drop_table('materia')
    op.drop_table('grupo')
    op.drop_table('experimento')
    op.drop_table('docente')
    # ### end Alembic commands ###
